profiles:
  dev:
    server:
      host: dev.internal
      mode: development
  prod:
    server:
      host: prod.internal
      mode: production
  canary:
    server:
      host: canary.internal
      mode: staging
